/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import javax.swing.JOptionPane;

/**
 *
 * @author ludimo16
 */
public class AppBase extends javax.swing.JFrame {
private Integer adminId;

    /**
     * Creates new form AppBase
     */
    public AppBase() {
        initComponents();
        bloquearComponentes(); // Bloquea los botones al inicio
        btnGuardarBD.setVisible(false); // Oculta el botón al inicio
        btnCargarBD.setVisible(false); // Oculta el botón al inicio
        btnAuditoria.setVisible(false); // Oculta el btn al inicio
        // Muestra el panel ViewLogin al iniciar la aplicación
        Utility.PanelPrint(content, new ViewLogin());
    }
    
    public void bloquearComponentes() {
        Configuracion.setEnabled(false);
        btnLibros.setEnabled(false);
        btnUsuarios.setEnabled(false);
        btnGuardarBD.setEnabled(false);
        btnCargarBD.setEnabled(false);
    }

    public void desbloquearComponentes() {
        Configuracion.setEnabled(true);
        btnLibros.setEnabled(true);
        btnUsuarios.setEnabled(true);
        btnGuardarBD.setEnabled(true);
        btnCargarBD.setEnabled(true);
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
        System.out.println("ID de Administrador almacenado en AppBase: " + adminId); // Depuración
    }

    public Integer getAdminId() {
        return adminId;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        Configuracion = new javax.swing.JToggleButton();
        btnGuardarBD = new javax.swing.JButton();
        btnCargarBD = new javax.swing.JButton();
        btnAuditoria = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        fondoDePantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setMaximumSize(new java.awt.Dimension(1500, 800));
        content.setMinimumSize(new java.awt.Dimension(1500, 800));
        content.setPreferredSize(new java.awt.Dimension(1500, 800));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        btnExit.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        btnExit.setText("X");
        btnExit.setPreferredSize(new java.awt.Dimension(75, 75));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 10, -1, -1));

        btnLibros.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        btnLibros.setText("Libros");
        btnLibros.setMaximumSize(new java.awt.Dimension(150, 50));
        btnLibros.setMinimumSize(new java.awt.Dimension(150, 50));
        btnLibros.setPreferredSize(new java.awt.Dimension(200, 50));
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        btnUsuarios.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setMaximumSize(new java.awt.Dimension(150, 50));
        btnUsuarios.setMinimumSize(new java.awt.Dimension(150, 50));
        btnUsuarios.setPreferredSize(new java.awt.Dimension(200, 50));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        Configuracion.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Configuracion.setText("Configuracion");
        Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(Configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnGuardarBD.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        btnGuardarBD.setText("Guardar Base de Datos");
        btnGuardarBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarBDMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 350, -1));

        btnCargarBD.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        btnCargarBD.setText("Cargar Base de Datos");
        btnCargarBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarBDMouseClicked(evt);
            }
        });
        getContentPane().add(btnCargarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 350, -1));

        btnAuditoria.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        btnAuditoria.setText("Auditoria");
        btnAuditoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAuditoriaMouseClicked(evt);
            }
        });
        getContentPane().add(btnAuditoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 350, -1));

        labelTitulo.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(153, 255, 255));
        labelTitulo.setText("BookShelter");
        labelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 5, true));
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 350, -1));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book_shelf_icon.png"))); // NOI18N
        labelLogo.setPreferredSize(new java.awt.Dimension(250, 250));
        getContentPane().add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        fondoDePantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimalist_books_image_1920x1080.png"))); // NOI18N
        getContentPane().add(fondoDePantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        Utility.PanelPrint(content, new ViewLibros());
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionActionPerformed
        // Alternar visibilidad de los botones
       boolean estadoActual = btnGuardarBD.isVisible(); // Verifica si los botones están visibles
       btnGuardarBD.setVisible(!estadoActual); // Cambia el estado al opuesto
       btnCargarBD.setVisible(!estadoActual); // Cambia el estado al opuesto
       btnAuditoria.setVisible(!estadoActual);  // Cambia el estado al opuesto
    }//GEN-LAST:event_ConfiguracionActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        Utility.PanelPrint(content, new ViewUsuarios());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnGuardarBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarBDMouseClicked
        Utility.crearCarpetaRespaldo();
        Utility.guardarBaseDeDatos();
        Utility.registrarAccion("auditoria_administradores", "El administrador guardó una copia de seguridad de la base de datos.", adminId);
    }//GEN-LAST:event_btnGuardarBDMouseClicked

    private void btnCargarBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarBDMouseClicked
        int confirmacion = JOptionPane.showConfirmDialog(
        null,
        "¿Estás seguro de que deseas sobreescribir la base de datos actual?",
        "Confirmación de Restauración",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        Utility.cargarBaseDeDatos();
        Utility.registrarAccion("auditoria_administradores", "El administrador cargó/restauró una copia de seguridad de la base de datos.", adminId);
    } else {
        System.out.println("Operación de restauración cancelada.");
    }
    }//GEN-LAST:event_btnCargarBDMouseClicked

    private void btnAuditoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAuditoriaMouseClicked
        Utility.PanelPrint(content, new ViewAuditoria());
    }//GEN-LAST:event_btnAuditoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Configuracion;
    private javax.swing.JButton btnAuditoria;
    private javax.swing.JButton btnCargarBD;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuardarBD;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fondoDePantalla;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}